<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="DESKTOP-BFS0L6V" failures="1" tests="1" name="Default test" time="12.743" errors="0" timestamp="05 Aug 2020 10:53:47 GMT">
  <testcase classname="com.justdial.test.JustdialTest" name="CheckTitel" time="0.43">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at com.justdial.test.JustdialTest.CheckTitel(JustdialTest.java:61)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- CheckTitel -->
  <testcase classname="com.justdial.test.JustdialTest" name="SearchTest" time="0.0">
    <ignored/>
  </testcase> <!-- SearchTest -->
  <testcase classname="com.justdial.test.JustdialTest" name="RattingTest" time="0.0">
    <ignored/>
  </testcase> <!-- RattingTest -->
  <testcase classname="com.justdial.test.JustdialTest" name="LocationSetTest" time="0.0">
    <ignored/>
  </testcase> <!-- LocationSetTest -->
  <testcase classname="com.justdial.test.JustdialTest" name="WeblinkTest" time="0.0">
    <ignored/>
  </testcase> <!-- WeblinkTest -->
  <testcase classname="com.justdial.test.JustdialTest" name="SelectDataTest" time="0.0">
    <ignored/>
  </testcase> <!-- SelectDataTest -->
</testsuite> <!-- Default test -->
